services:

  auth-service:
    build:
      context: ./auth-service
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    networks:
      - main-network

  learning-service:
    build:
      context: ./learning-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - database
    networks:
      - main-network

  leaderboard-service:
    build:
      context: ./leaderboard-service
    ports:
      - 8082:8082
    depends_on:
      - redis
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
    networks:
      - main-network

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: messenger-x
    ports:
      - 5432:5432
    networks:
      - main-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - main-network
    environment:
      - REDIS_PASSWORD=root

networks:
  main-network:
    driver: bridge